// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHSzrIPaSE-5tAfCgapWESC5NrbWdrMoE',
    appId: '1:254343291851:web:398e4e932ca8a0ad900c4e',
    messagingSenderId: '254343291851',
    projectId: 'talikify-user',
    authDomain: 'talikify-user.firebaseapp.com',
    storageBucket: 'talikify-user.firebasestorage.app',
    measurementId: 'G-948MTT33NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP8myDgVeiza71jbBFHbMf0BvppwR7WZw',
    appId: '1:254343291851:android:24888de6202b776e900c4e',
    messagingSenderId: '254343291851',
    projectId: 'talikify-user',
    storageBucket: 'talikify-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyIVUgz1S-4mg040U4l5KEBTz_VyytqDk',
    appId: '1:254343291851:ios:ae69c526eca7382f900c4e',
    messagingSenderId: '254343291851',
    projectId: 'talikify-user',
    storageBucket: 'talikify-user.firebasestorage.app',
    iosBundleId: 'com.example.receiverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyIVUgz1S-4mg040U4l5KEBTz_VyytqDk',
    appId: '1:254343291851:ios:ae69c526eca7382f900c4e',
    messagingSenderId: '254343291851',
    projectId: 'talikify-user',
    storageBucket: 'talikify-user.firebasestorage.app',
    iosBundleId: 'com.example.receiverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHSzrIPaSE-5tAfCgapWESC5NrbWdrMoE',
    appId: '1:254343291851:web:31a78f64dc1a5234900c4e',
    messagingSenderId: '254343291851',
    projectId: 'talikify-user',
    authDomain: 'talikify-user.firebaseapp.com',
    storageBucket: 'talikify-user.firebasestorage.app',
    measurementId: 'G-K99PP58M97',
  );

}